"""
Expand FrameMaker KBD_ friendly names into plain English descriptions.
Reads temp.csv, produces temp_expanded.txt with format:
    "friendly name": "expanded plain English"
with a blank line after each entry.

NOTE: this was used but can now be thrown away as the codename_to_friendlyname.py script was updated to produce the expanded names directly.
does all this. 
"""
import csv
import re

# ── Full entry overrides (friendlyname → expansion) ─────────────────────
OVERRIDES = {
    "hardhyphen": "hard hyphen",
    "hardreturn": "hard return",
    "hardspace": "hard space",
    "heatref": "heat reference",
    "help onlinemanuals": "help online manuals",
    "hide hotspotindicators": "hide hotspot indicators",
    "hishwindow": "history window",
    "hist": "history",
    "hotspot": "hotspot",
    "hotspotindicators": "hotspot indicators",
    "hotspotspod": "hotspots pod",
    "hscroll": "horizontal scroll",
    "hyprtxt shtcut": "hypertext shortcut",
    "incdash": "increment dash",
    "incfill": "increment fill",
    "incpen": "increment pen",
    "incwidth": "increment width",
    "indecross reference (XREF)s": "index cross references",
    "initcap": "initial capitals",
    "initcaph": "initial capitals here",
    "inline attredtr": "inline attribute editor",
    "input": "input",
    "insertobject": "insert object",
    "insertquick": "insert quick",
    "insetpod": "inset pod",
    "joincurves": "join curves",
    "kbmacro": "keyboard macro",
    "keeptool": "keep tool",
    "kerndown": "kern down",
    "kerndown6": "kern down 6",
    "kernhome": "kern home",
    "kernleft": "kern left",
    "kernleft6": "kern left 6",
    "kernright": "kern right",
    "kernright6": "kern right 6",
    "kernup": "kern up",
    "kernup6": "kern up 6",
    "lastpage": "last page",
    "lasttool": "last tool",
    "lgeqn": "large equation",
    "linelayout": "line layout",
    "linenumpro": "line number properties",
    "linenumtoggle": "line number toggle",
    "linetool": "line tool",
    "mancond": "manage conditions",
    "markerspod": "markers pod",
    "masterpage": "master page",
    "mathwindow": "math window",
    "medeqn": "medium equation",
    "memfail": "memory failure",
    "mem stats": "memory statistics",
    "menubarfocus": "menu bar focus",
    "menucomplete": "menu complete",
    "menucustom": "menu custom",
    "menumodify": "menu modify",
    "menuquick": "menu quick",
    "menureset": "menu reset",
    "minimize": "minimize",
    "mode rotate tool": "mode rotate tool",
    "movewindow": "move window",
    "newaframe": "new anchored frame",
    "newhypertext": "new hypertext",
    "newmarker": "new marker",
    "newmaster": "new master page",
    "newvar": "new variable",
    "nextpage": "next page",
    "nochangedb": "no change bar",
    "normalize tags": "normalize tags",
    "numlock": "num lock",
    "numspace": "numeric space",
    "obalign bottom": "object align bottom",
    "obalign center": "object align center",
    "obalign left": "object align left",
    "obalign middle": "object align middle",
    "obalign right": "object align right",
    "obalign top": "object align top",
    "objdown": "object down",
    "objleft": "object left",
    "objprops": "object properties",
    "objright": "object right",
    "objselect": "object select",
    "objselect nopref": "object select no preference",
    "objup": "object up",
    "openall": "open all",
    "openline": "open line",
    "openwindow": "open window",
    "open in popup win in": "open in popup window",
    "ovaltool": "oval tool",
    "pageback": "page back",
    "pagebreak": "page break",
    "pagelayout": "page layout",
    "pagesetup": "page setup",
    "pagesize": "page size",
    "pagestatus": "page status",
    "pageupdate": "page update",
    "pastespecial": "paste special",
    "pgfdesign": "paragraph design",
    "pgffmt delete": "paragraph format delete",
    "pgffmt delete unused": "paragraph format delete unused",
    "pgfquick": "paragraph quick",
    "pgfwindow": "paragraph window",
    "pickobjprops": "pick object properties",
    "podlocation": "pod location",
    "polygtool": "polygon tool",
    "polyltool": "polyline tool",
    "previewfba": "preview frame-based authoring",
    "preview acceptall": "preview accept all",
    "preview off": "preview off",
    "preview rejectall": "preview reject all",
    "prevpage": "previous page",
    "printsetup": "print setup",
    "putinline": "put inline",
    "quietclosewindow": "quiet close window",
    "quitall": "quit all",
    "quitwindow": "quit window",
    "randf": "replace and find",
    "recttool": "rectangle tool",
    "reference": "reference",
    "reformatdoc": "reformat document",
    "refpage": "reference page",
    "refreshwindow": "refresh window",
    "refresh ditamap rmvie": "refresh DITA map resource manager view",
    "rejectallchange": "reject all changes",
    "rejectchange": "reject change",
    "rejectchangeandnext": "reject change and next",
    "removeposter": "remove poster",
    "remove struct": "remove structure",
    "renameframe": "rename frame",
    "renamemarkertype": "rename marker type",
    "renameorplain": "rename or plain",
    "renamepage": "rename page",
    "reordermaster": "reorder master page",
    "repeatnew": "repeat new",
    "rerotate": "re-rotate",
    "resetdb": "reset database",
    "reshape": "reshape",
    "resizebox": "resize box",
    "resizeboxm": "resize box margins",
    "resizelock": "resize lock",
    "resizeunlock": "resize unlock",
    "restorefont": "restore font",
    "rglobal": "replace global",
    "rm mode": "review mode",
    "ronce": "replace once",
    "rotate ccw": "rotate counterclockwise",
    "rotate ccw small": "rotate counterclockwise small",
    "rotate cw": "rotate clockwise",
    "rotate cw small": "rotate clockwise small",
    "rotpage minus": "rotate page minus",
    "rotpage norm": "rotate page normal",
    "rotpage plus": "rotate page plus",
    "rot minus": "rotate minus",
    "rot plus": "rotate plus",
    "roundrect": "round rectangle",
    "rubiprops": "rubi properties",
    "saveall": "save all",
    "saveas": "save as",
    "saveasdbre": "save as database",
    "saveaspdf": "save as PDF",
    "saveaspdfreview": "save as PDF review",
    "saveaspdfreview2": "save as PDF review 2",
    "saveaspdfshare": "save as PDF share",
    "saveaspdfubiq": "save as PDF ubiquitous",
    "saveasxml": "save as XML",
    "savedbre": "save database",
    "savefmx": "save FrameMaker XML",
    "savemeta": "save metadata",
    "savesas": "save as",
    "searchreferences": "search references",
    "selectall": "select all",
    "select chapter compo": "select chapter composition",
    "setalign properties": "set align properties",
    "setcap": "set line cap style",
    "setcap 0": "set line cap style 0",
    "setcap 1": "set line cap style 1",
    "setcap 2": "set line cap style 2",
    "setcap 3": "set line cap style 3",
    "setcap option": "set line cap option",
    "setdash": "set dash pattern",
    "setdash 0": "set dash pattern 0",
    "setdash 1": "set dash pattern 1",
    "setdash 2": "set dash pattern 2",
    "setdash 3": "set dash pattern 3",
    "setdash 4": "set dash pattern 4",
    "setdash 5": "set dash pattern 5",
    "setdash 6": "set dash pattern 6",
    "setdash 7": "set dash pattern 7",
    "setdash 8": "set dash pattern 8",
    "setdash option": "set dash pattern option",
    "setdistribute properties": "set distribute properties",
    "setelcatall": "set element catalog all",
    "setelcatchild": "set element catalog child",
    "setelcatfreq": "set element catalog frequent",
    "setelcatloose": "set element catalog loose",
    "setelcatstrict": "set element catalog strict",
    "setfill": "set fill pattern",
    "setfill 0": "set fill pattern 0",
    "setfill 1": "set fill pattern 1",
    "setfill 2": "set fill pattern 2",
    "setfill 3": "set fill pattern 3",
    "setfill 4": "set fill pattern 4",
    "setfill 5": "set fill pattern 5",
    "setfill 6": "set fill pattern 6",
    "setfill 7": "set fill pattern 7",
    "setfill 8": "set fill pattern 8",
    "setfill 9": "set fill pattern 9",
    "setfill a": "set fill pattern A",
    "setfill b": "set fill pattern B",
    "setfill c": "set fill pattern C",
    "setfill d": "set fill pattern D",
    "setfill e": "set fill pattern E",
    "setfill f": "set fill pattern F",
    "setfromcolor": "set from color",
    "setknockout": "set knockout",
    "setoverprint": "set overprint",
    "setpen": "set pen pattern",
    "setpen 0": "set pen pattern 0",
    "setpen 1": "set pen pattern 1",
    "setpen 2": "set pen pattern 2",
    "setpen 3": "set pen pattern 3",
    "setpen 4": "set pen pattern 4",
    "setpen 5": "set pen pattern 5",
    "setpen 6": "set pen pattern 6",
    "setpen 7": "set pen pattern 7",
    "setpen 8": "set pen pattern 8",
    "setpen 9": "set pen pattern 9",
    "setpen a": "set pen pattern A",
    "setpen b": "set pen pattern B",
    "setpen c": "set pen pattern C",
    "setpen d": "set pen pattern D",
    "setpen e": "set pen pattern E",
    "setpen f": "set pen pattern F",
    "setposter": "set poster",
    "setrun properties": "set run-in properties",
    "setsearch": "set search",
    "setsep": "set color separation",
    "setsep all": "set color separation all",
    "setsep keep": "set color separation keep",
    "setsep reset tint over": "set color separation reset tint overprint",
    "setsides": "set sides",
    "setsolid": "set solid",
    "settint": "set tint",
    "setwidth": "set width",
    "setwidth 0": "set width 0",
    "setwidth 1": "set width 1",
    "setwidth 2": "set width 2",
    "setwidth 3": "set width 3",
    "setwidth option": "set width option",
    "setwidth slide": "set width slide",
    "set textframe grid": "set text frame grid",
    "shftspace": "shift space",
    "shownext": "show next",
    "showprev": "show previous",
    "show borders": "show borders",
    "show condition ind": "show condition indicator",
    "show element context av": "show element context availability",
    "show hotspotindicator": "show hotspot indicator",
    "smalltoolwindow": "small tool window",
    "smeqn": "small equation",
    "softhyphen": "soft hyphen",
    "spellreset": "spelling reset",
    "splitl": "split left",
    "splitr": "split right",
    "spoptions": "spelling options",
    "strip flowstructure": "strip flow structure",
    "strwindow": "structure window",
    "strwin leftanchor": "structure window left anchor",
    "stuff item": "stuff item",
    "stylefmt delete": "style format delete",
    "stylefmt delete unuse": "style format delete unused",
    "symfont": "symbol font",
    "tablewindow": "table window",
    "table addrc": "table add rows and columns",
    "table cellfmt": "table cell format",
    "table exit ip": "table exit insertion point",
    "table resizecol": "table resize column",
    "table rowfmt": "table row format",
    "tagstatus": "tag status",
    "tblfmt delete": "table format delete",
    "tblfmt delete unused": "table format delete unused",
    "tblip above": "table insertion point above",
    "tblip below": "table insertion point below",
    "tblip bottom": "table insertion point bottom",
    "tblip left": "table insertion point left",
    "tblip leftmost": "table insertion point leftmost",
    "tblip next": "table insertion point next",
    "tblip previous": "table insertion point previous",
    "tblip right": "table insertion point right",
    "tblip rightmost": "table insertion point rightmost",
    "tblip top": "table insertion point top",
    "tblip topleft": "table insertion point top left",
    "tblsel cell": "table select cell",
    "tblsel celltext": "table select cell text",
    "tblsel column": "table select column",
    "tblsel colbody": "table select column body",
    "tblsel row": "table select row",
    "tblsel table": "table select table",
    "table dialog paste repl": "table dialog paste replace",
    "table dialog unify cf": "table dialog unify cell format",
    "table dialog unify tf": "table dialog unify table format",
    "tc search book": "track changes search book",
    "tc search ditamap": "track changes search DITA map",
    "tc search document": "track changes search document",
    "tc search selection": "track changes search selection",
    "tc user name": "track changes user name",
    "test printdbre": "test print database",
    "textcolpro": "text column properties",
    "textltool": "text left-to-right tool",
    "textrtool": "text right-to-left tool",
    "thinspace": "thin space",
    "toggledraw": "toggle draw",
    "toggle struct and do": "toggle structure and document",
    "toolbar base": "toolbar base",
    "toolbar hideall": "toolbar hide all",
    "toolbar showall": "toolbar show all",
    "toolwindow": "tool window",
    "trackchangedisable": "track change disable",
    "uialertstrings pref": "UI alert strings preference",
    "uncond": "unconditional",
    "varcurdate": "variable current date",
    "varcurpg": "variable current page",
    "varother": "variable other",
    "varpgcount": "variable page count",
    "varquick": "variable quick",
    "verifycontext": "verify context",
    "view api shortcut": "view API shortcut",
    "view switch": "view switch",
    "vscroll": "vertical scroll",
    "width0": "width 0",
    "width1": "width 1",
    "windowfull down": "window full page down",
    "windowfull up": "window full page up",
    "win cascade": "window cascade",
    "win tile": "window tile",
    "wrapquick": "wrap quick",
    "xchars": "special characters",
    "xrefspod": "cross references pod",
    "zoom100": "zoom 100 percent",
    "zoomin": "zoom in",
    "zoomout": "zoom out",
}

INPUT  = r"c:\GIT\Z_Master_Rag\Train_Embed_Model\temp.csv"
OUTPUT = INPUT  # overwrite in place

lines_out = []
with open(INPUT, newline="", encoding="utf-8") as f:
    reader = csv.reader(f)
    for row in reader:
        # skip blank rows
        if not row or all(c.strip() == "" for c in row):
            continue
        # columns: 0=count, 1=category, 2=codename, 3=friendlyname, 4=(empty)
        if len(row) < 4:
            continue
        friendly = row[3].strip()
        if not friendly:
            continue

        expanded = OVERRIDES.get(friendly)
        if expanded is None:
            # fallback: just use the friendly name as-is (shouldn't happen)
            expanded = friendly
            print(f"WARNING: no override for '{friendly}'")

        lines_out.append(f'"{friendly}": "{expanded}"')

with open(OUTPUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines_out) + "\n")

print(f"Wrote {len(lines_out)} entries to {OUTPUT}")
